name: Update Serving Model

on: workflow_dispatch

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Copy model config
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_HOST_TF_SERVING }}
        username: ec2-user
        port: 22
        key: ${{ secrets.SSH_KEY_TF_SERVING }}
        source: "bert-tf-serving/models.config"
        target: "/home/ec2-user/model"
        strip_components: 1
    
    - name: Restart TF-Serving
      uses: appleboy/ssh-action@master   
      env:
       MODEL_VERSION: ${{ secrets.MODEL_VERSION }}     
      with:
        host: ${{secrets.DEPLOYMENT_HOST_TF_SERVING}}
        username: ec2-user
        key: ${{ secrets.SSH_KEY_TF_SERVING }}
        port: 22
        envs: GITHUB_SHA, MODEL_VERSION
        script: |
          rm -rf /home/ec2-user/model/saved_model_bert/*
          aws s3 cp s3://alanyeung-bert-chatbot/saved_model_bert/$MODEL_VERSION /home/ec2-user/model/saved_model_bert/$MODEL_VERSION --recursive
          docker stop bert-tf-serving
          docker rm bert-tf-serving
          docker run --detach \
            --name bert-tf-serving \
            -p 8501:8501 \
            --mount type=bind,source=/home/ec2-user/model/saved_model_bert,target=/models/bert-multilingual-chatbot \
            --mount type=bind,source=/home/ec2-user/model/models.config,target=/models/models.config \
            -e MODEL_NAME=bert-multilingual-chatbot \
            -t tensorflow/serving \
            --model_config_file=/models/models.config 
